Fabrid validation at source
jeltevanbommel/scionlab pull request #6
Opened 2024-10-05 12:49 UTC by rohrerj

Contains code for FABRID validation at source. This PR is only created to help with code comparison and review and should therefore not directly be merged. Feature not fully implemented.

2025-01-08 09:24 UTC, jeltevanbommel commented
*[`pkg/snet/path/fabrid.go` line 189 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4DMoxB7nNdeOma2-W:-OG4DMoxB7nNdeOma2-X:bsv2blz) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/snet/path/fabrid.go#L189)):*
> ```Go
> 		})
> 
> 	if f.pathKey != nil {
> ```

Can we refactor this into multiple function calls? It's a lot of lines for the method right now, helps with readability.


<!-- Sent from Reviewable.io -->

2025-01-08 09:29 UTC, jeltevanbommel commented
*[`router/cmd/router/main.go` line 160 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4EeBqEgJMWS19P-bW:-OG4EeBqEgJMWS19P-bX:b-91mz1x) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/router/cmd/router/main.go#L160)):*
> ```Go
> 			BatchSize:             globalCfg.Router.BatchSize,
> 		}
> 		dp.DataPlane.Fabrid = globalCfg.Router.Fabrid
> ```

I wouldn't assign here, rather add it to the dataplane struct when it's initialized


<!-- Sent from Reviewable.io -->

2025-01-08 09:35 UTC, jeltevanbommel commented
*[`private/app/path/path.go` line 143 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4FsMpCZ_8pbNLPSuc:-OG4FsMpCZ_8pbNLPSud:b9x2ir) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/private/app/path/path.go#L143)):*
> ```Go
> 			return resPath, nil
> 		}
> 		if o.interactive && len(validFabridPaths) != 0 {
> ```

Rather than duplicating all this logic, I think it makes more sense to create the list of paths here / enhance the list with the selected policies, and then pass it to the existing o.interactive printAndChoose.



_Code snippet:_
```Go
	if o.interactive {
		selectedPath, err = printAndChoose(paths, remote, o.colorScheme)
		if err != nil {
			return selectedPath, err
		}
	} else {
		selectedPath = paths[rand.Intn(len(paths))]
	}
```


<!-- Sent from Reviewable.io -->

2025-01-08 09:43 UTC, jeltevanbommel commented
*[`demo/fabrid/main.go` line 306 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4I62EDkEqopilFHvX:-OG4I62EDkEqopilFHvY:b-l6mwxj) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/demo/fabrid/main.go#L306)):*
> ```Go
> type client struct {
> 	network *snet.SCIONNetwork
> 	//conn    *snet.Conn
> ```

remove


<!-- Sent from Reviewable.io -->

2025-01-08 09:47 UTC, jeltevanbommel commented
*[`demo/fabrid/README.md` line 3 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4ItOxEt3dSWm2Kmrc:-OG4ItOxEt3dSWm2Kmrd:b6iay7l) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/demo/fabrid/README.md#L3)):*
> ```Markdown
> # FABRID demo
> 
> This demo shows how two hosts can obtain a shared key with the DRKey system.
> ```

This description is for the wrong demo


<!-- Sent from Reviewable.io -->

2025-01-08 09:55 UTC, jeltevanbommel commented
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 263 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4KhwL7PnGlSUbCPZz:-OG4KhwL7PnGlSUbCP_-:b-l6mwxj) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L263)):*
> ```Go
> 
> 	err := macBlock(pathKey, tmpBuf, macInputBuf[:fcMacInputLength], resultBuffer)
> 	//log.Debug("Computing FABRID control validator",
> ```

remove


<!-- Sent from Reviewable.io -->

2025-01-08 09:55 UTC, jeltevanbommel commented
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 281 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4KkS82sQIo8VYRLXh:-OG4KkS82sQIo8VYRLXi:b-l6mwxj) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L281)):*
> ```Go
> 	}
> 	outBuffer[0] &= 0xF // ignore first four bits
> 	//log.Debug("Computing FABRID control validator",
> ```

remove


<!-- Sent from Reviewable.io -->

2025-01-08 09:55 UTC, jeltevanbommel commented
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 297 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4Km8_4aLJyN4xXzvT:-OG4Km8_4aLJyN4xXzvU:b-l6mwxj) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L297)):*
> ```Go
> 	}
> 	computedValidator[0] &= 0xF // ignore first four bits
> 	//log.Debug("Verifying FABRID control validator",
> ```

remove


<!-- Sent from Reviewable.io -->

2025-01-08 10:01 UTC, jeltevanbommel commented
*[`pkg/snet/path/fabrid.go` line 189 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4DMoxB7nNdeOma2-W:-OG4M55s9INuhnLo9QyD:b-eotfxr) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/snet/path/fabrid.go#L189)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Can we refactor this into multiple function calls? It's a lot of lines for the method right now, helps with readability.
</blockquote></details>

Also instead of a long if statement like this:



_Code snippet:_
```Go
if f.pathKey == nil {
	return nil
}
```


<!-- Sent from Reviewable.io -->

2025-01-08 10:10 UTC, jeltevanbommel commented
*[`private/app/path/path.go` line 126 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4O9OrDMnO2KCKlj_Z:-OG4O9OrDMnO2KCKlj__:bhkb3su) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/private/app/path/path.go#L126)):*
> ```Go
> 			}
> 			fabridPath, err := snetpath.NewFABRIDDataplanePath(scionPath, p.Metadata().Hops(),
> 				pols.Policies(), &o.fabrid.FabridConfig, 0, conn.FabridKeys)
> ```

Shouldn't the validation ratio be configurable with some option?


<!-- Sent from Reviewable.io -->

2025-01-08 10:13 UTC, jeltevanbommel commented
*[`pkg/experimental/fabrid/server/server.go` line 14 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4ObYx7a4inLwkQH9h:-OG4ObYx7a4inLwkQH9i:b-j1hnwn) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/server/server.go#L14)):*
> ```Go
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

Is this the right location for this file? Also some documentation here would be nice, it's a bit unclear what this 'server' would be used for.


<!-- Sent from Reviewable.io -->

2025-01-08 10:14 UTC, jeltevanbommel requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/6)* status: all files reviewed, 10 unresolved discussions (waiting on @rohrerj)



<!-- Sent from Reviewable.io -->

2025-01-08 14:37 UTC, rohrerj reviewed
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/6)* status: 19 of 29 files reviewed, 10 unresolved discussions (waiting on @jeltevanbommel)

___
*[`demo/fabrid/main.go` line 306 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4I62EDkEqopilFHvX:-OG4en6L7vQIf5_I7ppP:b-896fix) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/demo/fabrid/main.go#L306)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`demo/fabrid/README.md` line 3 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4ItOxEt3dSWm2Kmrc:-OG4hJ-n8gM1Ux59XwEV:b-8cmsvw) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/demo/fabrid/README.md#L3)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

This description is for the wrong demo
</blockquote></details>

Oh, I should have read the readme. I wrote now one that matches the actual test.
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 263 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4KhwL7PnGlSUbCPZz:-OG4haZO89Pru8fn0l1B:b-896fix) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L263)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 281 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4KkS82sQIo8VYRLXh:-OG4hbA3EWpUmUjvgP7d:b-896fix) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L281)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`pkg/experimental/fabrid/crypto/fabrid_crypto.go` line 297 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4Km8_4aLJyN4xXzvT:-OG4hbX194V60QUfbJWl:b-896fix) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/experimental/fabrid/crypto/fabrid_crypto.go#L297)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`pkg/snet/path/fabrid.go` line 189 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4DMoxB7nNdeOma2-W:-OG52nw7CtTpnlrGVXWu:b-bchp30) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/pkg/snet/path/fabrid.go#L189)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Also instead of a long if statement like this:
</blockquote></details>

I moved the code for setting the control options extension to a seperate function
___
*[`private/app/path/path.go` line 126 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4O9OrDMnO2KCKlj_Z:-OG4rUrI7DTi5fmSoua7:bh0utdl) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/private/app/path/path.go#L126)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Shouldn't the validation ratio be configurable with some option?
</blockquote></details>

I moved the validation ratio into the FabridConfig. With this it can now be configured
___
*[`private/app/path/path.go` line 143 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4FsMpCZ_8pbNLPSuc:-OG52Jgi6ZyEwtSc-5uk:bfnbbty) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/private/app/path/path.go#L143)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

Rather than duplicating all this logic, I think it makes more sense to create the list of paths here / enhance the list with the selected policies, and then pass it to the existing o.interactive printAndChoose.
</blockquote></details>

I modified it
___
*[`router/cmd/router/main.go` line 160 at r1](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG4EeBqEgJMWS19P-bW:-OG52kCU85j3j4ixEOAx:b499q7j) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/fb8e8d12da013ca932510a809032d2e7a7ee0ebc/router/cmd/router/main.go#L160)):*
<details><summary><i>Previously, jeltevanbommel (jelte) wrote…</i></summary><blockquote>

I wouldn't assign here, rather add it to the dataplane struct when it's initialized
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2025-01-08 15:44 UTC, jeltevanbommel commented
*[`pkg/snet/path/fabrid.go` line 199 at r2](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-OG5_Te51aRAhw9G5pKu:-OG5_Te51aRAhw9G5pKv:b-ecrks3) ([raw file](https://github.com/jeltevanbommel/scionlab/blob/61dcccbbad7bbdb8638479db8f277cb1154be831/pkg/snet/path/fabrid.go#L199)):*
> ```Go
> 		}
> 	}
> 	f.counter++
> ```

Shouldn't this be inside of the if statement?  (compared to last commit)


<!-- Sent from Reviewable.io -->

2025-01-08 15:45 UTC, jeltevanbommel reviewed
> Reviewed 9 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/6)* status: 28 of 29 files reviewed, 2 unresolved discussions (waiting on @rohrerj)



<!-- Sent from Reviewable.io -->

2025-04-08 11:51 UTC, jeltevanbommel approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/jeltevanbommel/scionlab/6#-:-ONKEV9_CawL_Js7e2Ke:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rohrerj)



<!-- Sent from Reviewable.io -->

2025-04-09 13:47 UTC, closed without merging